### ISSUE TITLE
[BUG?] 2FA failed.

### ISSUE THREAD

**Issue by mzch** [diced/zipline#52]
**Describe the bug**
I can't enable 2FA.

**To Reproduce**
1. Click `ENABLE 2FA`
2. Scan Code
3. Enter 6 digit code and click `UNABLE`
4. Nothing happened.

**Expected behavior**
Enable 2FA

**Screenshots**
<img width="551" alt="スクリーンショット 2020-12-07 19 38 01" src="https://user-images.githubusercontent.com/621178/101341235-1c088d00-38c4-11eb-9779-cdb2269d1593.png">

**Desktop (please complete the following information if desktop):**
 - OS: macOS 11.0.1 (Big Sur)
 - Browser: Chrome
 - Zipline Version: 2.5.8

**Browser Logs (for desktop browsers)**
See screen shot.

**Comment by diced** [comment]
fixed, a commit will be out within the next with with tons of other stuff & bug fixes
