### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by adolphin-hitler** [diced/zipline#57]
I like this webserver very much, easy to setup. But I want to use https with it, is there a way to do it within this server or I've to do something with nginx or smth.

**Comment by hexed** [comment]
Using nginx.

**Comment by hexed** [comment]
Assuming you use certbot

`server {
    server_name    <DOMAIN>;

    location / {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
        proxy_pass         http://127.0.0.1:8870;
        client_max_body_size 2G;
    }
    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/<DOMAIN>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<DOMAIN>/privkey.pem;
ssl_dhparam /etc/nginx/ssl/dhparam.pem;
}

server {
    if ($host = <DOMAIN>) {
        return 301 https://$host$request_uri;
    } 

    listen         80;
    server_name    cdn.proximity.sh;
    return 404; # managed by Certbot
}`

**Comment by diced** [comment]
Yes, I don't think ill be making zipline have https it self, so you will  need to use nginx or apache, etc. Another way is to just use cloudflare with flexible ssl if you dont want to deal with certs.
