### ISSUE TITLE
Able to create more than one initial admin users [BUG]

### ISSUE THREAD

**Issue by NatsumiHB** [diced/zipline#62]
**Describe the bug**

**To Reproduce**
1. Install Zipline and do the initial setup (through Docker in our case)
2. Go to `/user/setup`

**Expected behavior**
You shouldn't be able to go through the initial setup again. Going to that subdirectory is possible for anyone and poses a big security risk as it means anyone can just create an administrative account.

**Screenshots**
!["Bug Screenshot 1"](https://btw.i-use-ar.ch/i/7nzlfujy.png "Bug Screenshot 1")

**Desktop (please complete the following information if desktop):**
 - OS: Windows 10 Pro 20H2
 - Browser: Firefox Developer Edition
 - Zipline Version: Newest upstream (self-built image with newest code from repo as of February 2)
^ This shouldn't be important for the bug as it seems to be backend-related

**Browser Logs (for desktop browsers)**
```
Not applicable for this bug
```

**Comment by diced** [comment]
user/setup is accessible only when it's first setup, after you setup you can't access the page again

**Comment by NatsumiHB** [comment]
I tested it earlier and was able to access the setup page AFTER it's setup, so that's clearly not true.

If you want me to I can record a video of the bug later.

**Comment by diced** [comment]
Sure, I did reproduce this and it didn't happen for me.

**Comment by NatsumiHB** [comment]
I don't know what the issue is then. The person whose server I administer created the original administrative account and I can navigate to https://i.example.com/user/setup and get access to that initial setup page.

EDIT as I was trying to record: It appears that I now get a "could not create" when attempting to do it again, which is really baffling since the bug did clearly exist (for our version at least) and just poofed into the void.

Any pointers on what could have caused this?

**Comment by diced** [comment]
I'd guess some browser cache or something, not sure what happened. What database are you using?

**Comment by NatsumiHB** [comment]
SQLite, this happened to a person who didn't load it before and to me in two different browsers (Firefox and Edge)

**Comment by diced** [comment]
as I'm not able to reproduce this the only way of fixing this on your end would be to delete the sql db file and I think it should work fine after that

**Comment by NatsumiHB** [comment]
Gotcha, I think that's not necessary as the bug resolved itself but I'll do some further testing later. If I find something interesting I'll try to fix it and send a PR. You can close this now as it's resolved. Thank you for your time!

**Comment by diced** [comment]
Np!
