### ISSUE TITLE
Manage Profile - Getting Unexpected Error [BUG]

### ISSUE THREAD

**Issue by Tetrahedron789** [diced/zipline#69]
**Describe the bug**
When going to manage profile, getting unexpected error screen

**To Reproduce**
1. Go to 'Manage Profile'

**Expected behavior**
Probably see the manage profile page

**Screenshots**
https://tetra.wtf/u/fyjR.png

**Desktop (please complete the following information if desktop):**
 - OS: Windows 10
 - Browser: Opera GX
 - Zipline Version: 2.8.1

**Browser Logs (for desktop browsers)**
https://tetra.wtf/u/fqa8.png

**Comment by diced** [comment]
not able to reproduce, send your config (remove sensitive data!)
