### ISSUE TITLE
Fix metatags in Head

### ISSUE THREAD

**Issue by TheRealHeyJack** [diced/zipline#71]
**Is your feature request related to a problem? Please describe.**
Metatags don't copy over to most Head attributes e.g. page title

**Describe the solution you'd like**
Metatags to go into config

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by NoodlesDev987** [comment]
There should be added config field to set custom meta tags: title, description, theme-color, site_name, og:image

**Comment by diced** [comment]
This will be fixed in an upcoming release of zipline
