### ISSUE TITLE
Add oauth support

### ISSUE THREAD

**Issue by NoodlesDev987** [diced/zipline#75]
Add Discord, Github, Google, ... auth support for easier log in. This should be optional and configurable in config file

**Comment by laundmo** [comment]
could there please be a reason given why this was closed @diced ? just not going to implement that or already exists or what?

**Comment by diced** [comment]
> could there please be a reason given why this was closed @diced ? just not going to implement that or already exists or what?

Because Zipline isn't supposed to be a image host that is largely available to many users, its just supposed to be something for friends, etc.
