### ISSUE TITLE
Default username/password (or config for them)?

### ISSUE THREAD

**Issue by laundmo** [diced/zipline#78]
hey, just installed zipline v3 for the first time, what is the default username/password? i cant find any info anywhere, and common ones like `admin` `admin` and `username` `password` dont work.

**Comment by LeviSnoot** [comment]
It's `administrator` and `password`

**Comment by laundmo** [comment]
thanks! could this be added to the documentation somewhere?

**Comment by LeviSnoot** [comment]
We'll have to see what diced says, but fyi that info appears when you do `npm run start`

**Comment by diced** [comment]
Username: administrator 
Password: password

I'll make sure to add this to the documentation as requested, thanks!

**Comment by laundmo** [comment]
> We'll have to see what diced says, but fyi that info appears when you do `npm run start`

its kinda hard to notice when running in docker, as by default `docker-compose up -d` hides the log, and looking at them later it might be quite far up.

ideally, there would also be a environment variable for configuring a different default username/password.

also, @diced could you please leave issues open until they have been addressed? would be nice if this could have been left open until the documentation was added for others to easily find.
