### ISSUE TITLE
Cannot upload image to server

### ISSUE THREAD

**Issue by AlphaNecron** [diced/zipline#84]
![image](https://user-images.githubusercontent.com/57827456/130343888-3c233bbb-e792-46dc-b61c-b24d371be7e9.png)
Any fixes for this?
Using `next` branch btw.

**Comment by diced** [comment]
not sure, send your config

**Comment by diced** [comment]
and next branch is unsupported now, please use the trunk `branch`

**Comment by AlphaNecron** [comment]
> `next` branch is unsupported now, please use the `trunk` branch

How can i get Discord embed to work btw?
